<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Custom throw error</title>
</head>
<body>
    <h2>JavaScript try catch</h2>

    <p>Please input a number between 5 and 10:</p>
    
    <input id="demo" type="text" placeholder="enter a number">
    <button type="button" onclick="myFunction()">Test Input</button>
    <br/><br/>
    <p id="p01"></p>
    
    <script>
    function myFunction() {
      const message = document.getElementById("p01");
      message.innerHTML = "";
      let x = document.getElementById("demo").value;
      //trim() trim's spaces present in the input
      //here using throw keyword we are giving custom error msg to catch block & display it.
      try { 
        if(x.trim() == "")  throw "empty";
        if(isNaN(x)) throw "not a number";
        x = Number(x); // typcasting of input number
        if(x < 5)  throw "too low";
        if(x > 10)   throw "too high";
      }
      catch(error) {
        message.innerHTML = "Input is " + error;
      }finally{
        console.log("finally block executed irrespective of error occured or not");
        document.getElementById("demo").value="";//textbox value become blank so that user again give input
      }
    }
    </script>
    
</body>
</html>